name: Docker Image CI

on:
  push:
    branches: 'v[0-9]*\.[0-9]*'
    
jobs:
  build:
    if: ${{ startsWith(github.event.head_commit.message, '#NORUN') == false }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
